### ISSUE TITLE
Provider detection incorrect on Arch Linux

### ISSUE THREAD

**Issue by Tajnymag** [ashwinvis/xrandr-extend#1]
xrandr-extend incorrectly checks Intel GPUs under "Intel\n". It should be "intel\n" without the beginning capital letter.

After editing the script, xrandr-extend runs correctly.

**Comment by ashwinvis** [comment]
Updated the script. Does that work for you?

**Comment by Tajnymag** [comment]
Yes, the issue has been resolved. Thank you
