### ISSUE TITLE
Offset screen after execution

### ISSUE THREAD

**Issue by kovasap** [ashwinvis/xrandr-extend#10]
* xrandr-extend version: 0.2.0
* Python version: 3.7.5
* Operating System: linux based on ubuntu

### Description

Ran the tool, and ended up with shifted screen problems.  For instance, half of one monitor was black and 2/3 of the other was.  The windows were shifted so that half of them appeared off the screen.  Messing with -pos changed this slightly, but I wasn't able to get it to line up properly.  

Is there an option I'm missing perhaps?

### What I Did

```
$ xrandr-extend hdmi
xrandr --auto
xrandr --listmonitors
xrandr --output eDP-1 --auto --output HDMI-1 --auto --scale 1.67x1.67 --right-of eDP-1
xrandr --output eDP-1 --scale 0.9999x0.9999
Monitors: 2
 0: +*eDP-1 1920/309x1080/173+1920+0  eDP-1
 1: +HDMI-1 1920/509x1080/286+0+0  HDMI-1
```

**Comment by ashwinvis** [comment]
Did you try the `--pan` and `--pos` flags?

**Comment by ashwinvis** [comment]
Hi @kovasap you forgot to edit the xrandr-extend configuration!

Both your monitors are 1080p, while the default configuration is for a 4K + 1080p monitor setup, and it tries to run `--scale 1.67x1.67`. Hope that answers your question. 

For you this tool might be overkill. Just use a shell alias or a function:

```sh
xrandr --output eDP-1 --output HDMI-1 --right-of eDP-1
```

**Comment by NikosAlexandris** [comment]
> Did you try the `--pan` / `--pos` flags?

What are the possible arguments for `--pos`?

**Comment by ashwinvis** [comment]
@NikosAlexandris Those are just boolean flags, and they execute different commands:

https://github.com/ashwinvis/xrandr-extend/blob/a181d520cf650dd1f0a9d093e2e9c22155492fd3/src/xrandr_extend/main.py#L154-L177

**Comment by ashwinvis** [comment]
Guess we can close this now...
