### ISSUE TITLE
How to set the provider based off xrandr --listmonitors

### ISSUE THREAD

**Issue by sebastian-ruiz** [ashwinvis/xrandr-extend#12]
* xrandr-extend version: 0.2.0
* Python version: 3.7
* Operating System: Ubuntu 20.04

### Description

I would like to run my two monitors with the high resolution monitor set to double scaling and the other at native resolution. I don't know how to interpret the `xrandr --listproviders` output.

### What I Did

I have two monitors:
```
xrandr --listmonitors
Monitors: 2
 0: +*DP-4 4096/480x2304/270+0+0  DP-4
 1: +DP-3 1920/518x1200/324+4096+0  DP-3
```
and I have:
```
xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x1b8 cap: 0x1, Source Output crtcs: 4 outputs: 9 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x1f9 cap: 0x6, Sink Output, Source Offload crtcs: 2 outputs: 1 associated providers: 1 name:modesetting
```
I am unsure how to write the `[provider:..]` section of the config file. So far I have:

```
[provider:modesetting]
primary = DP-4
secondary = DP-3

#[provider:NVIDIA-0]
#primary = 
#secondary =

[resolutions]
primary = 4096, 2304
secondary = 1920, 1200

[scaling]
primary = 2.0
secondary = 1.0
```
The primary monitor is an ultrafine 4k and needs to scaled to 200%. The second display is some standard office Dell monitor. Both monitors are driven from an Nvidia graphics card, however for the ultrafine display, the the display port cable from the graphics card first goes into a pcie adapter card which converts the display port to display port over usb-c, since the monitor is usb-c only.

Thank you for your help and the package!

**Comment by ashwinvis** [comment]
Hi @sebastian-ruiz, apologies! I might have missed the notification.

Your configuration looks good to me. Could you describe what happens when you execute it?

**Comment by ashwinvis** [comment]
As for display providers like NVIDIA-0, there was a bug which should be fixed in #8. I should release the fix soon. Can you check if you install the git master version it works?

**Comment by sebastian-ruiz** [comment]
Hi, I decided to use autorandr instead. Thank you for your help anyway.

**Comment by ashwinvis** [comment]
That's fine. But if your time permits, it would be helpful if you can clarify what was the issue.
