### ISSUE TITLE
Support rotation

### ISSUE THREAD

**Issue by FFY00** [ashwinvis/xrandr-extend#6]
* xrandr-extend version: 0.2.0
* Python version: 3.7.4
* Operating System: Archlinux

### Description

Would it be possible to support screen rotation? Currently I have a 4k screen in horizontal and a 1080p screen in vertical on the right side.

**Comment by ashwinvis** [comment]
Interesting proposition. `xrandr --help` shows that `--rotate normal,inverted,left,right` is possible. Feel free to modify `main.py` to include this option and send a pull request.

**Comment by akihironitta** [comment]
@ashwinvis Can I give it a go for this as a PR for Hacktoberfest?

**Comment by ashwinvis** [comment]
Fixed in #14
